/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef, useLayoutEffect, useMemo } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import * as THREE from 'three'

export default function RockStone(props) {
  const pivotRef = useRef()   // 👈 rotate THIS (Theatre / editable)
  const modelRef = useRef()   // 👈 actual meshes live here

  const { nodes, materials } = useGLTF('/models/Rock-Product-New-5.glb')

  /* ---------- texture / material (unchanged) ---------- */
  // const rockTex = useTexture('/textures/rock-texture.jpg')
  // useMemo(() => {
  //   rockTex.wrapS = rockTex.wrapT = THREE.RepeatWrapping
  //   rockTex.repeat.set(2, 2)
  // }, [rockTex])

  // const rockMaterial = useMemo(
  //   () =>
  //     new THREE.MeshStandardMaterial({
  //       map: rockTex,
  //       roughness: 1,
  //       metalness: 0.1,
  //       displacementScale: 0.05,
  //     }),
  //   [rockTex]
  // )

  /* ---------- CENTER PIVOT FIX ---------- */
  useLayoutEffect(() => {
    if (!modelRef.current || !pivotRef.current) return

    // make sure matrices are correct
    pivotRef.current.updateWorldMatrix(true, true)

    // bounding box of the whole model
    const box = new THREE.Box3().setFromObject(modelRef.current)
    const center = new THREE.Vector3()
    box.getCenter(center)

    // convert world center → pivot local space
    pivotRef.current.worldToLocal(center)

    // move model so pivot origin = model center
    modelRef.current.position.sub(center)
  }, [])

  return (
    <group ref={pivotRef} {...props} dispose={null}>
      <group ref={modelRef}>
      <group position={[0.116, 5.567, 8.305]} rotation={[-Math.PI / 2, 0, 0]} scale={2.397}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={nodes.Object_2.material}
          position={[0.089, -0.456, -0.055]}
          rotation={[0, 0, 0.19]}
          scale={0.575}
        />
      </group>
      <group position={[-7.658, -7.233, 7.562]} rotation={[-Math.PI / 2, 0, 0]} scale={7.618}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2012.geometry}
          material={nodes.Object_2012.material}
          position={[0.241, 0.35, 0.499]}
          rotation={[1.135, -0.142, 0.065]}
        />
      </group>
      <group position={[0.294, 3.597, 7.69]} rotation={[-1.8, 0.682, 0.331]} scale={1.651}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2001.geometry}
          material={nodes.Object_2001.material}
          position={[-0.836, 0.394, -0.521]}
          scale={0.778}
        />
      </group>
      <group position={[-1.351, 1.53, 8.475]} rotation={[-1.8, 0.682, 0.331]} scale={1.565}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2002.geometry}
          material={nodes.Object_2002.material}
          position={[-0.663, 1.997, 1.224]}
          rotation={[0, -1.204, 0]}
          scale={0.778}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={nodes.Cube002.material}
        position={[2.955, 6.278, 4.109]}
        rotation={[0, 0.14, 0]}
        scale={[1.665, 0.401, 0.716]}
      />
      <group position={[-0.171, 1.367, 4.206]} rotation={[-Math.PI / 2, 0, 0]} scale={1.9}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2003.geometry}
          material={nodes.Object_2003.material}
          scale={0.575}
        />
      </group>
      <group position={[5.02, 1.728, 4.82]} rotation={[-Math.PI / 2, 0, -0.581]} scale={2.397}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2004.geometry}
          material={nodes.Object_2004.material}
          position={[1.448, -1.226, 1.309]}
          rotation={[0, 0, 2.584]}
          scale={[0.386, 0.339, 0.575]}
        />
      </group>
      <group
        position={[3.504, 2.226, 5.159]}
        rotation={[-2.767, 0, 0.187]}
        scale={[1.33, 2.2, 2.226]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2005.geometry}
          material={nodes.Object_2005.material}
          position={[0.62, -1.032, 1.483]}
          rotation={[0, 0, 2.584]}
          scale={[0.386, 0.339, 0.575]}
        />
      </group>
      <group
        position={[4.75, 6.247, 5.529]}
        rotation={[-2.819, 0.096, 0.31]}
        scale={[0.902, 1.491, 1.509]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2006.geometry}
          material={nodes.Object_2006.material}
          position={[0.62, -1.032, 1.483]}
          rotation={[0, 0, 2.584]}
          scale={[0.386, 0.339, 0.575]}
        />
      </group>
      <group position={[4.467, -0.212, -0.102]} rotation={[-Math.PI / 2, 0, 0]} scale={1.9}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2007.geometry}
          material={nodes.Object_2007.material}
          position={[-0.542, -0.5, 0.349]}
          rotation={[-0.523, -0.199, 2.801]}
          scale={[0.635, 0.413, 0.642]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={nodes.Cube003.material}
        position={[0.956, 3.753, 1.213]}
        rotation={[0, 0.593, 0]}
        scale={[1.665, 0.401, 0.716]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube001.material}
        position={[2.729, 5.406, 2.939]}
        rotation={[0, Math.PI / 9, 0]}
        scale={[1.665, 0.401, 0.716]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={nodes.Cube004.material}
        position={[1.915, 4.519, 2.004]}
        rotation={[0, 0.593, 0]}
        scale={[1.665, 0.401, 0.716]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={nodes.Cube005.material}
        position={[-1.129, 1.548, -1.063]}
        rotation={[0, 0.593, 0]}
        scale={[1.665, 0.401, 0.716]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={nodes.Cube007.material}
        position={[0.357, 3.034, 0.542]}
        rotation={[0, 0.593, 0]}
        scale={[1.665, 0.401, 0.716]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={nodes.Cube006.material}
        position={[-0.314, 2.458, -0.273]}
        rotation={[0, 0.593, 0]}
        scale={[1.665, 0.401, 0.716]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={nodes.Cube008.material}
        position={[-2.112, 0.877, -1.878]}
        rotation={[0, 0.81, 0]}
        scale={[1.665, 0.401, 0.716]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={nodes.Cube009.material}
        position={[-3.144, 0.054, -2.138]}
        rotation={[0, 1.16, 0]}
        scale={[1.665, 0.401, 0.716]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={nodes.Cube010.material}
        position={[-4.365, -0.798, -1.906]}
        rotation={[0, 1.535, 0]}
        scale={[1.665, 0.401, 0.716]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube011.geometry}
        material={nodes.Cube011.material}
        position={[-5.411, -1.609, -1.033]}
        rotation={[-Math.PI, 1.379, -Math.PI]}
        scale={[1.665, 0.401, 0.716]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube012.geometry}
        material={nodes.Cube012.material}
        position={[-6.61, -2.376, -0.41]}
        rotation={[-Math.PI, 1.11, -Math.PI]}
        scale={[1.665, 0.401, 0.716]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube013.geometry}
        material={nodes.Cube013.material}
        position={[-7.473, -3.124, 0.463]}
        rotation={[-Math.PI, 0.731, -Math.PI]}
        scale={[1.665, 0.401, 0.716]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube014.geometry}
        material={nodes.Cube014.material}
        position={[-7.962, -3.967, 1.638]}
        rotation={[-Math.PI, 0.527, -Math.PI]}
        scale={[1.665, 0.401, 0.716]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube015.geometry}
        material={nodes.Cube015.material}
        position={[-8.138, -4.846, 2.805]}
        rotation={[-Math.PI, 0.31, -Math.PI]}
        scale={[1.665, 0.401, 0.716]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube016.geometry}
        material={nodes.Cube016.material}
        position={[-8.214, -5.576, 4.129]}
        rotation={[-Math.PI, 0.189, -Math.PI]}
        scale={[1.665, 0.401, 0.716]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube017.geometry}
        material={nodes.Cube017.material}
        position={[-8.122, -6.344, 5.156]}
        rotation={[Math.PI, -0.076, Math.PI]}
        scale={[1.665, 0.401, 0.716]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube018.geometry}
        material={nodes.Cube018.material}
        position={[-7.797, -7.027, 6.432]}
        rotation={[Math.PI, -0.28, Math.PI]}
        scale={[1.665, 0.401, 0.716]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube019.geometry}
        material={nodes.Cube019.material}
        position={[-6.99, -8.037, 7.477]}
        rotation={[Math.PI, -0.451, Math.PI]}
        scale={[1.665, 0.401, 0.716]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube020.geometry}
        material={nodes.Cube020.material}
        position={[-6.024, -8.752, 8.547]}
        rotation={[Math.PI, -0.692, Math.PI]}
        scale={[1.665, 0.401, 0.716]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube021.geometry}
        material={nodes.Cube021.material}
        position={[-4.901, -9.473, 9.352]}
        rotation={[Math.PI, -0.95, Math.PI]}
        scale={[1.665, 0.401, 0.716]}
      />
      <group position={[-1.296, -5.314, 1.952]} rotation={[-2.277, -0.116, 1.683]} scale={1.565}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2008.geometry}
          material={nodes.Object_2008.material}
          position={[0.107, 1.631, 1.883]}
          rotation={[0, -1.204, 0]}
          scale={0.654}
        />
      </group>
      <group position={[-1.424, -4.175, 10.065]} rotation={[-1.8, 0.682, 0.331]} scale={1.565}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2009.geometry}
          material={nodes.Object_2009.material}
          position={[0.001, 2.128, 2.085]}
          rotation={[0, -1.204, 0]}
          scale={0.778}
        />
      </group>
      <group
        position={[-2.261, 0.388, 6.454]}
        rotation={[2.356, 0.429, 2.387]}
        scale={[0.77, 1.419, 0.768]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2010.geometry}
          material={nodes.Object_2010.material}
          position={[0.342, 2.176, 2.094]}
          rotation={[-0.04, -0.389, 0.49]}
          scale={0.778}
        />
      </group>
      <group
        position={[-4.604, -0.243, 8.824]}
        rotation={[2.356, 0.429, 2.387]}
        scale={[0.77, 1.419, 0.768]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2011.geometry}
          material={nodes.Object_2011.material}
          position={[-3.125, 2.516, 6.035]}
          rotation={[-2.383, -0.288, -2.093]}
          scale={0.778}
        />
      </group>
      <group position={[-7.078, -9.053, 8.487]} rotation={[-Math.PI / 2, 0, 0]} scale={7.618}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2013.geometry}
          material={nodes.Object_2013.material}
          position={[0.476, 0.362, 0.528]}
          rotation={[1.266, -0.198, 0.103]}
          scale={1.713}
        />
      </group>
      <group position={[-1.217, -3.258, -2.89]} rotation={[-1.109, -0.317, -0.084]} scale={7.618}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2014.geometry}
          material={nodes.Object_2014.material}
          position={[0.235, 0.406, 0.438]}
          rotation={[1.135, -0.142, 0.065]}
        />
      </group>
      <group position={[-1.552, -2.842, -2.032]} rotation={[-2.104, 0.777, 0.48]} scale={0.951}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2015.geometry}
          material={nodes.Object_2015.material}
          position={[-0.663, 1.997, 1.223]}
          rotation={[0, -1.204, 0]}
          scale={0.778}
        />
      </group>
      <group
        position={[-5.788, -4.729, -1.447]}
        rotation={[-2.452, 0.918, 0.826]}
        scale={[0.952, 1.348, 1.078]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2016.geometry}
          material={nodes.Object_2016.material}
          position={[-0.663, 1.997, 1.224]}
          rotation={[0, -1.204, 0]}
          scale={0.778}
        />
      </group>
      <group position={[-7.658, -7.233, 7.562]} rotation={[-Math.PI / 2, 0, 0]} scale={7.618}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2018.geometry}
          material={nodes.Object_2018.material}
          position={[-0.12, 1.058, 0.334]}
          rotation={[0.595, -0.285, 0.163]}
          scale={[1.244, 1.109, 1.118]}
        />
      </group>
      <group
        position={[-7.657, -6.491, -2.051]}
        rotation={[-2.738, -0.18, 1.481]}
        scale={[0.952, 1.348, 1.078]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2017.geometry}
          material={nodes.Object_2017.material}
          position={[-0.665, 1.151, 1.767]}
          rotation={[-2.522, -1.371, -2.59]}
          scale={0.778}
        />
      </group>
      <group
        position={[-7.751, -7.828, 1.164]}
        rotation={[2.102, -0.708, 1.034]}
        scale={[0.952, 1.348, 1.078]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2019.geometry}
          material={nodes.Object_2019.material}
          position={[-1.689, 0.998, 1.412]}
          rotation={[-2.522, -1.371, -2.59]}
          scale={0.615}
        />
      </group>
      <group position={[-10.882, -6.125, 8.26]} rotation={[-2.598, -0.343, 0.2]} scale={7.618}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2020.geometry}
          material={nodes.Object_2020.material}
          position={[0.241, 0.35, 0.499]}
          rotation={[1.135, -0.142, 0.065]}
        />
      </group>
      <group position={[-9.479, -7.311, 9.491]} rotation={[-2.598, -0.343, 0.2]} scale={7.618}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2021.geometry}
          material={nodes.Object_2021.material}
          position={[0.202, 0.322, 0.365]}
          rotation={[1.221, -0.026, 0.998]}
        />
      </group>
      <group
        position={[-0.021, -10.18, 8.308]}
        rotation={[2.338, -0.736, 1.001]}
        scale={[0.952, 1.348, 1.078]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2022.geometry}
          material={nodes.Object_2022.material}
          position={[-2.823, -0.222, 2.638]}
          rotation={[-2.017, -0.65, -2.431]}
          scale={0.513}
        />
      </group>
      <group position={[-4.143, -7.455, 11.502]} rotation={[-1.917, -1.173, 1.257]} scale={7.618}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2023.geometry}
          material={nodes.Object_2023.material}
          position={[0.436, 0.369, 0.704]}
          rotation={[1.312, -1.222, 0.109]}
        />
      </group>
      <group position={[-5.455, -4.2, 12.144]} rotation={[2.46, 0.225, 1.595]} scale={7.618}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2024.geometry}
          material={nodes.Object_2024.material}
          position={[0.324, 0.461, 0.705]}
          rotation={[1.312, -1.222, 0.109]}
        />
      </group>
      <group position={[-5.507, -7.07, 9.526]} rotation={[1.723, 0.225, 1.595]} scale={2.735}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2025.geometry}
          material={nodes.Object_2025.material}
          position={[0.324, 0.461, 0.705]}
          rotation={[1.312, -1.222, 0.109]}
          scale={1.281}
        />
      </group>
      <group position={[-6.657, -4.695, 6.435]} rotation={[-1.263, -0.087, -0.077]} scale={9.013}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2026.geometry}
          material={nodes.Object_2026.material}
          position={[0.241, 0.349, 0.497]}
          rotation={[1.135, -0.142, 0.065]}
        />
      </group>
      <group position={[6.254, 2.166, 6.874]} rotation={[-Math.PI / 2, 0, 2.004]} scale={2.397}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2027.geometry}
          material={nodes.Object_2027.material}
          scale={0.575}
        />
      </group>
      <group position={[6.122, 2.605, 2.038]} rotation={[-Math.PI / 2, 0, 2.732]} scale={1.669}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2028.geometry}
          material={nodes.Object_2028.material}
          position={[-0.206, -0.123, -0.303]}
          scale={0.575}
        />
      </group>
      <group position={[0.81, 11.018, 10.587]} rotation={[-2.421, 0.473, -0.093]} scale={7.618}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2029.geometry}
          material={nodes.Object_2029.material}
          position={[0.168, 0.679, 0.122]}
          rotation={[0.999, -0.018, 0.875]}
          scale={[1.949, 1.652, 1.324]}
        />
      </group>
    </group>
    </group>
  )
}

useGLTF.preload('/models/Rock-Product-New-5.glb')
